### ISSUE TITLE
Small suggestions and notes

### ISSUE THREAD

**Issue by tin2tin** [snuq/VSEQF#10]
Could the .frame_start value be used for showing sync, when a movie and a sound strip with the same basename are parented and .frame_start match, by changing the color of the parent line to ex. green(as in green-light go) in that case?

Is the Speed Step widget needed in the header? Or maybe it could be moved into the Time Line header?

Vertical zoom can be set like this: https://devtalk.blender.org/t/on-view2d-zoom-in-out/3563/4

Maybe you could add the Quick Cuts menu to the Strip menu? It's more logic to find edit operations in the menus, than in the sidebar, imo. As a rule of thumb, keep strip&tool settings in the sidebar and edit functions in the menu. The various VSEQF pop-up menus maybe also should be accessible from the menu, so their short-cuts will be visible in the UI.   

Should the Timeline menu(from the Quick Cuts menu) be added to the context menu for right clicking in empty time line area too? Could be added to the View menu too. 

Maybe the Quick Cuts menu would be faster to read if there are sub menus for Left/Right options and the icons where removed(in native Blender only Add menu entries are allowed icons).

Playhead is now the official name for the previous called Time Cursor(See the select menu) - VSEQF is using Cursor as name

It is very hard to find the 3 point Edit function in the bottom of the left sidebar in the File Browser pop up, maybe it could be moved to the right sidebar instead(in pop up and not in VSE workspace)?

To ease the use of 3 point edit, when importing the clip, and no clip editor is found, the preview area could be split and the right sidebar of the clip editor could be auto opened(left closed?) and the the set in/out function is auto executed(This will save users a lot of steps).

Maybe it would be better to move the In/Out lines to the bottom, so they won't collide with the zoom gizmo? 

Having in and out on the same line would be more elegant, but I guess that this is the only way to get it to work?

Maybe timecode layout could be used in the panel instead? (to save vertical space)

In Avid the two ways to add a strip is by insert(as it is in VSEQF(respecting sync)) and overwrite, which cuts a hole in the current strip and add the new strip into the old strip - I don't think this it currently possible?

BTW. I posted about your draw volume level feature on Twitter, and it is getting a lot of love: https://twitter.com/rintworin/status/1207203074621792256

**Comment by snuq** [comment]
> Is the Speed Step widget needed in the header? Or maybe it could be moved into the Time Line header?

Good idea, moved it


> Vertical zoom can be set like this: https://devtalk.blender.org/t/on-view2d-zoom-in-out/3563/4

Wont work in this case, thats relative zoom, i need to be able to get/set the absolute zoom level... without any way of at least detecting the zoom level, that operator is useless in my case


> Maybe you could add the Quick Cuts menu to the Strip menu? It's more logic to find edit operations in the menus, than in the sidebar, imo. As a rule of thumb, keep strip&tool settings in the sidebar and edit functions in the menu. The various VSEQF pop-up menus maybe also should be accessible from the menu, so their short-cuts will be visible in the UI.

Quick cuts will eventually be toolbar elements, once thats added. for now, it will stay as a panel because clicking buttons is a lot easier than finding a submenu in my my opinion.


> Should the Timeline menu(from the Quick Cuts menu) be added to the context menu for right clicking in empty time line area too? Could be added to the View menu too.

Im not liking the idea of putting it in the view menu as that just modifies how the timeline is viewed, where quick timeline will actually change the timeline... I do like the idea of putting it in the context menu tho and in the header instead of a panel.


> Maybe the Quick Cuts menu would be faster to read if there are sub menus for Left/Right options and the icons where removed(in native Blender only Add menu entries are allowed icons).

Excessive submenus are not quick to navigate by any means... the arrows are there to help differentiate between the left and right cuts.  I have rearranged the menu a bit tho, all the left and right operations are now arranged together, i think its a bit more readable this way.


> It is very hard to find the 3 point Edit function in the bottom of the left sidebar in the File Browser pop up, maybe it could be moved to the right sidebar instead(in pop up and not in VSE workspace)?

I dont think i can put a panel on the right side, that is where the settings go... it doesnt appear to have any functionality to actually put a panel there.


> To ease the use of 3 point edit, when importing the clip, and no clip editor is found, the preview area could be split and the right sidebar of the clip editor could be auto opened(left closed?) and the the set in/out function is auto executed(This will save users a lot of steps).

I dont really like the idea of changing the user's interface on them... i dont know of any parts of blender that do this, and it really seems like a rude thing to do to the user for me.  Going straight to the set in/out is an interesting idea. Problem is, im planning on expanding the usage of the clip editor for other pre-editing functionality like adding tags and otherwise organizing footage.  The current 3point implementation is just the beginning of that.


> Maybe it would be better to move the In/Out lines to the bottom, so they won't collide with the zoom gizmo?

I dont think this is a problem as the zoom cant be used while setting the in/out anyway... besides, putting it at the bottom conflicts with the position setting, which can be used while setting the in/out.


> Maybe timecode layout could be used in the panel instead? (to save vertical space)

The whole point of splitting the minutes/seconds/frames into their own variables is so you can manually type in timecodes more easily rather than having to convert frames to a timecode in your head.  If the timecode boxes actually implement some way of setting minutes/seconds, then ill be happy to use those.


> In Avid the two ways to add a strip is by insert(as it is in VSEQF(respecting sync)) and overwrite, which cuts a hole in the current strip and add the new strip into the old strip - I don't think this it currently possible?

hmm, not exactly... i dont see much point in having that tho as it sounds like the same thing as 'import at cursor', really

**Comment by tin2tin** [comment]
A way to think of Menus is that they are a catalogue of functions paired with their shortcuts, which means that the main function of the menus is not necessarily for quick access, but for allowing the user to learn about all the possible options and their shortcuts(without having to consult the manual). For an example, take a look at the extreamly packed menus of the default 3D View. 

If import at cursor does the same(I'm not at my computer), then maybe using the more industry standard wording 'overwrite(at cursor)', could be helpful for users?

Is it possible to add a the 3pe button next to the footer of the pop up file browser(next to add and cancel)?

Most of these suggestions are for making the UI of VSEQF functions a bit more in consistency with the UI philosophy of Blender, so users might encounter your add-on with a less steep learning curve, but I respect that that you know what is a more effective UI for a better workflow, so I'll close this.
