### ISSUE TITLE
Cannot install addon in version 2.92

### ISSUE THREAD

**Issue by ghost** [snuq/VSEQF#12]
![image](https://user-images.githubusercontent.com/66299057/100599082-dcf49d80-32ff-11eb-9dcc-9020cbd9d3bd.png)
After installing, at the moment of enabling the addon, the following error appears: "... already registered as a subclass ..."

**Comment by snuq** [comment]
Please note that I don't test my addons on the pre-release versions of Blender, and I often am a bit late on updating (if I have an ongoing project, I will wait on updating).
There were a couple other errors in the release version of Blender 2.92, which have now been fixed, but I did not encounter this one.

If you are still encountering this error with the latest version and the release version of Blender 2.92, please let me know, otherwise I am closing this for now.
