### ISSUE TITLE
Marker Improvements

### ISSUE THREAD

**Issue by asbestosbill** [snuq/VSEQF#19]
Markers should be affected by ripple edits. I can't think of a case where I would want a marker to stay where it was when the thing it marked got moved back.

When dragging markers, it would be useful to snap (possibly via a modifier) to cuts and the current frame. I see that holding Ctrl snaps movement to full-second increments, which is interesting but my initial thought is that it might be better to snap to full seconds on the timeline. Lastly, if there's a "Jump Cursor to This Marker" menu option, the opposite would also be nice.

Another useful feature would be the ability to copy the marker list to the clipboard. YouTube chapters are [defined](https://support.google.com/youtube/answer/9884579?hl=en) by listing timecodes in the video description, starting with 00:00. It would be very convenient for a YouTube workflow if one could just paste those in.

**Comment by snuq** [comment]
The ripple markers sounds like a good idea, ill add that to my todo list.

I dont currently extend the marker moving tool at all.  Unfortunately, Blender makes expanding these tools a huge pain, and snapping to cuts and strips would be nice, but it would take a lot more work than its worth.  I dont see myself having the time to add this.  
I can add a 'snap selected marker to cursor' option in the snap menu tho.  Ill also add a 'cursor to nearest marker' snap option as well.

I dont know about adding the marker list export as an option in VSEQF, but it could be added as a button script in ScriptShortcuts (would probably export it into a text editor area rather than the clipboard, not sure if putting it on the clipboard is possible)

**Comment by snuq** [comment]
Added ripple markers, various shortcuts for marker snapping to both the snap menu and the marker/cursor context menus.

Also made a quick timeline marker export script over on my ScriptShortcut addon: https://github.com/snuq/Script-Shortcut/blob/master/buttons/vse/Export%20Markers.py
It can be run directly from a blender text editor area, or by using ScriptShortcut to make a button.
