### ISSUE TITLE
Timeline Rippled has no Effect

### ISSUE THREAD

**Issue by EroAxe** [snuq/VSEQF#22]
As the title describes, I've used the master version and the released version both to no avail with the VSE, I am on a bit of a later version attempting to do so (3.4 to be exact) and nothing happens when trying to use the feature, besides the default behaviour of it snapping back to the original position.

**Comment by snuq** [comment]
I will need some more information as it is working for me on blender 3.4:
First, when you grab a strip, do you see the 'Grab' text in the bottom-left corner of the strip? does this text change to 'Ripple' when you press alt?
Second, please open the system console (Blender's menus - 'Window' -> 'Toggle System Console') and let me know if there are any messages that are added to that console when you try to engage grab and/or ripple.  If there are, please paste those messages.

**Comment by EroAxe** [comment]
Sorry for being so late with the response, I just double checked just to make sure and seems like it was on me.  I assumed holding vs pressing Alt would have the same effect, but apparently not.  So it works if I select a strip then only *press* Alt, it works.  Otherwise it does not.

Although I did also stumble across another issue with Power Sequencer enabled, should I open another issue for that ?  The TLDR is it seems to disable timeline ripple & parenting of strips.

**Comment by snuq** [comment]
> Although I did also stumble across another issue with Power Sequencer enabled, should I open another issue for that ? The TLDR is it seems to disable timeline ripple & parenting of strips.

I'm not familiar at all with power sequencer, but it sounds like it is using its own variation on the grab function, or directly calling blender's built in grab function instead of vseqf's.  Unfortunately, thats not really something I can do anything about on my end.  A way to test if this is the case would be to try using a dedicated vseqf shortcut: alt+numpad5.

There are a couple possible fixes: First, you can uninstall both addons, then install power sequencer first, then vseqf - whichever is installed last will override the shortcuts of the first one.  Second, you can edit your shortcuts and manually assign shortcuts to the vseqf.grab operator.

**Comment by EroAxe** [comment]
Hmm, I'll have to look into that second option, as for the first one though, Power Sequencer is bundled with Blender for a few versions now, so I definitely installed it second, I assume maybe it takes priority since it's bundled or something.
