### ISSUE TITLE
Error when running from text area

### ISSUE THREAD

**Issue by tin2tin** [snuq/VSEQF#3]
I'm getting this error when left clicking in left click mode(ran the add on from the text editor and didn't install it):
![image](https://user-images.githubusercontent.com/1322593/62806453-2a3d7200-baf3-11e9-80b6-409cdf24b5af.png)

**Comment by snuq** [comment]
Huh.  well, it has nothing to do with it being left click mode or anything else... it seems that property registration using the : instead of = only works in blender classes... not a general 'object' class... what.
Fixed now, but this seems to be a bug in Blender, not sure why its doing this, I might have to undo this change later.

**Comment by snuq** [comment]
Alright, not a blender bug I guess, just a misunderstanding of how blender properties work on my part.  Regardless, those properties are not needed for the temp settings class.

**Comment by tin2tin** [comment]
Great, works now.
