### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by tin2tin** [snuq/VSEQF#4]
Not bugs, but a little feedback:

Opening it, again totally impressed by how much you managed to add to your toolset. 

Maybe I just become accustomed to have box select as default left click(in open space) behavior, but I'm missing it in VSEQF.

If audio strips aren't aligned directly under their parented movie strip, maybe the attachment line could get a different color like red, to signify that the audio may be out of sync. 
(I thought first that the small number inside the strips is the sync offset(it was next to the attachment line), but then realized that it was the duration. 

Grab(under strip) is now called 'Move' in 2.80. The number is written on top of the Grab word when 20+ channels are shown and the strips are narrow. 

Are Transitions available in the context menus?

The snap functions in the strip menu, maybe could be attached to the Transform menu(there there also are snap to playhead functions). SEQUENCER_MT_strip_transform

I think I would move the Quick Function Settings into the header after Strips. The same goes for Quick Cuts. They deserve to be full menus in the header. The menus will works as a representation of the included functions/tools, event though people access them through context menus or the panel.

Tags in the Right Click Menu seems to be empty?

Love the Quick List. Maybe the filename could be enabled/disabled to make it more clear what strip is selected? (maybe instead of the outline, which makes the list move on selection?) 

In the sidebar, I think you should keep the strip properties related stuff in the Strip panel, but move the rest into a Tools tab, so the strip panel will not become too long. And tags and markers could have a tab of their own.

All for now. Congratulations on your most excellent add-on.

**Comment by snuq** [comment]
Wow, lots of stuff, ok here we go,

> Maybe I just become accustomed to have box select as default left click(in open space) behavior, but I'm missing it in VSEQF.

Hmm, that IS a bug, I dont use left-click mode, I didnt realize it was behaving incorrectly

> If audio strips aren't aligned directly under their parented movie strip, maybe the attachment line could get a different color like red, to signify that the audio may be out of sync.

I dont know about this, since parenting can work with any strip to any other strip... some method to display out-of-sync audio is on my radar, but its not something I really think about.

> Grab(under strip) is now called 'Move' in 2.80. The number is written on top of the Grab word when 20+ channels are shown and the strips are narrow.

It's called 'Move' but the shortcut is 'G'...? great, that makes perfect sense... I think ill just leave it as 'Grab' :p
About the text position tho, not entirely sure what to do about this, its hard to determine exactly how big and where the text needs to be...

> The snap functions in the strip menu, maybe could be attached to the Transform menu(there there also are snap to playhead functions). SEQUENCER_MT_strip_transform

Good idea, ill add that to my todo

> I think I would move the Quick Function Settings into the header after Strips. The same goes for Quick Cuts. They deserve to be full menus in the header. The menus will works as a representation of the included functions/tools, event though people access them through context menus or the panel.

I can see a point to giving quick function settings its own menu... im a bit split on it tho, it would help the user to know there are settings there, but im also afraid of cluttering the header too much.
Well, quick cuts already has a panel and a popup menu, I didnt think adding another instance of it was needed.
Honestly tho, quick cuts should be popout menu in the tools panel i think, ill put it there once we have one.

> Tags in the Right Click Menu seems to be empty?

Have you made any tags to add? it will be empty if there are no tags created...

> Love the Quick List. Maybe the filename could be enabled/disabled to make it more clear what strip is selected? (maybe instead of the outline, which makes the list move on selection?)

The outline denotes the active strip, the strip type enabled/disabled denotes if it is selected or not.  I agree this isnt the best, ill give it some thought on a better way to convey this information.  Tho, not through disabling the strip name, then the user would not be able to rename non-selected strips.

> In the sidebar, I think you should keep the strip properties related stuff in the Strip panel, but move the rest into a Tools tab, so the strip panel will not become too long. And tags and markers could have a tab of their own.

Once the toolbar is put in, ill be doing some reworking of the panels, popups, and menus to put everything where it should be.  Ill reevaluate the panels and categories at that time too.
Right now im thinking of making another tab for 'timeline' or something, that includes things like the markers, and maybe other things.

**Comment by tin2tin** [comment]
On the sync thing, maybe if the parent-child strips share the same name and duration then the attachment line(s) could have a different colour if the frames do not match.

**Comment by snuq** [comment]
Fixed the box select bug, and moved the snapping menu in the latest master.

Reworking QuickList to be a bit more obvious on selections is on my todo, a possibility of displaying some sort of offset for desynced audio is on my 'future possibilities' todo.

I thought about putting quick functions settings in its own menu... but my only options are to put it at the start of the header, or the end of the header:
At the start, means its before the 'Sequencer' menu even, not really a good thing.
At the end, means its after that big spacer after the menus...
Unfortunately, neither of these options are a good one, so its going to have to stay inside the view menu.

I think that resolves everything you have brought up in this topic, am I missing anything?
Also, if you have any other suggestions in the future, id love to hear them, but it would be better to put them in separate topics (easier to manage via github).

**Comment by tin2tin** [comment]
Cool. I've submitted a patch to remove that redundant spacer, so appended add-on menus will be placed right after the default menus: https://developer.blender.org/D5511 (in Sequencer mode)
(I hope this will be accepted without much trouble)

The Strip sidebar is currently very long, maybe you could consider adding cut/fades etc. into a Tools tab and Markers/Tags into a separate tab too? 
The idea is the only Strip properties are in the Strip panel and everything else are in their own panels. Maybe that will give you some more vertical space to make the panel less wide?

**Comment by snuq** [comment]
> Cool. I've submitted a patch to remove that redundant spacer, so appended add-on menus will be placed right after the default menus

Hmm, that spacer is quite nice tho when you want to append buttons and stuff to be separated from the menus...

> The Strip sidebar is currently very long, maybe you could consider adding cut/fades etc. into a Tools tab and Markers/Tags into a separate tab too?
> The idea is the only Strip properties are in the Strip panel and everything else are in their own panels. Maybe that will give you some more vertical space to make the panel less wide?

Yeah, a full rework of the panels is on my todo list, but I want to wait until the tools panel is available so I can move some things to it.
I think tags would be in the strip tab, since they are applied to the strips, but markers will most likely be moved to its own/different tab

**Comment by tin2tin** [comment]
This way you have the choice to add your own spacer. :-)

Yes, Good point on Tags.

**Comment by tin2tin** [comment]
Maybe this one can be closed too?

**Comment by snuq** [comment]
Sure, feel free to let me know if you have any other suggestions/comments tho
